### ISSUE TITLE
Feature Request: Modular build tasks

### ISSUE THREAD

**Issue by Dangoo** [sinnerschrader/patternplate#142]
At a certain level the build-task `build-bundles` becomes pretty slow. Sometimes after doing some adjustments on only one type of files (e.g. styles) it might get handy to build just those files.

So we may consider to split the tasks `build-bundles` into modular pieces…
* `build-bundles:css`
* `build-bundles:js`
* `build-bundles:<format>`

…and then combining them into `build-bundles` on the one hand side but also exposing them as stand alone build tasks to improve build-speed for specific output formats.

```shell
$ patternplate console build-bundle:css
```

Even better would be an optional configuration parameter passed to the task to build only specific formats like this:

```shell
$ patternplate console build-bundle -- --formats css
```

This needs further benchmarking and testing…

**Comment by marionebl** [comment]
I am all in for the idea the give users some degree of control over the work done by all the build tasks. I favor the approach using parameters instead of new gulp-style subtasks:

> `$ patternplate console build-bundle -- --formats css`

As far as i recall most of the infrastructure, e.g. passing a [minimist](https://github.com/substack/minimist) flags/params object into the build tasks should already in place.

I'd like to keep the recognized options and their names as near to the current file-based configuration as possible. This should help us cutting down on doubled maintenance and out-of-sync problems with the general config and cli diverging later on.

**Comment by 2075** [comment]
so it is short-term feasible or not? :)

**Comment by marionebl** [comment]
@2075 Nobody is actively working on this. The source for `build-bundles` is located at [application/tasks/build-bundles/index.js](https://github.com/sinnerschrader/patternplate-server/blob/master/source/application/tasks/build-bundles/index.js#L22). Interested in giving this a shot?

**Comment by marionebl** [comment]
Obsolete as patternplate will move towards a dev/design tool without own transform chain.
