### ISSUE TITLE
Hands-on meeting

### ISSUE THREAD

**Issue by Xiphe** [sinnerschrader/patternplate#20]
As a result of #14 we'd like to meet somewhere a bit more quiet, to get our hands dirty and play around with this project.

Here is a doodle: http://doodle.com/poll/p9a5r75hxzb8kkzi

For Jimdo we'd like to evaluate if we could switch the tooling of our ui-library to patternplate

For the patternplate project this could lead to new insights and we could write some documentation for setup, common questions and how to work with the patternplate

We can also work on the JSX to everything compiler (change name and add link here).

**Comment by Xiphe** [comment]
cc @lassediercks @bjoernjimdo @christian-meyer-jimdo @filtercake @HerrBertling @marcroman @yaaan @KarstenBuckstegge

**Comment by marionebl** [comment]
thanks @Xiphe!

**Comment by HerrBertling** [comment]
:+1:

**Comment by p0wl** [comment]
would love to join (filled out the doodle, looks like we have a favorite)!

**Comment by KarstenBuckstegge** [comment]
@marionebl what about with the S2 posse? I guess some of them would be interested in that topic as well but I don't see them in the doodle. Also, I guess it could get problematic with the meeting time at Friday morning if a few of them want to join...

**Comment by Xiphe** [comment]
Friday 11.03. 11:00  - 15:00 looks promising. I blocked our "Melmac" Confi, that should suite 8-10 People. Will add details later on.

**Comment by marionebl** [comment]
Hey @KarstenBuckstegge, @Xiphe and all! Looking forward to this; I'll ping the S2 colleagues tomorrow about this.

**Comment by KarstenBuckstegge** [comment]
Roundup of the meeting on 3-11-2016:

- We mainly took a in depth look at both solutions
- the common opinion was, that both sides can benefit from each others accomplishments, ideas and knowledge 
- Jimdo pointed out the following patternplate features as the ones that could be useful:
  - Dependency Graph
  - JSX Templates
  - Demo Pages  
- S2 pointed out the following ui-library features as the ones that could be useful:
  - External documentation pages besides the main pattern library
  - feature development and reviews based on github issues and pull-requests
- Especially the opportunity to build JSX-to-X-transforms that both systems could use equally was pointed out
- As a conclusion we agreed to meet again on a friday in the near future (possibly the 1st of april)
- The aim of the next meeting was set to "get our hands dirty" and get started with a first JSX transform.


In order to find a fitting date I created another doodle. Please fill it out here:
http://doodle.com/poll/m8vxqt77vndxnfxr

**Comment by KarstenBuckstegge** [comment]
@marionebl if you'd add your answer we can nail down the next meetup date. ;)

**Comment by marionebl** [comment]
@KarstenBuckstegge Answered, thanks for the reminder

**Comment by KarstenBuckstegge** [comment]
@marionebl
Because of a important meeting that came up on the 01.04. that nearly all Jimdos have to attend we had to cancel the set date. In order to find a new time, please update your answer in the doodle.
Muchas mercis.
http://doodle.com/poll/m8vxqt77vndxnfxr
